### ISSUE TITLE
Set up the allcontributors bot to acknowledge contributors.

### ISSUE THREAD

**Issue by adswa** [adswa/git-annex-remote-osf#1]
You can find instructions on how to do so [here](https://allcontributors.org/docs/en/bot/overview). Note that you need to be added as a collaborator on this project first, so please get in touch if you want to do this. 

If the bot is enabled, add yourself as a contributor right away. :)

**Comment by adswa** [comment]
@DorienHuijser, would you want to tackle this? :)

**Comment by DorienHuijser** [comment]
Yes, I will look into this asap! Nice beginner task for me :)

**Comment by adswa** [comment]
wohoo! :tada:

**Comment by adswa** [comment]
Installation is done, would you test it? :)
