### ISSUE TITLE
Github usernames

### ISSUE THREAD

**Issue by adswa** [adswa/git-annex-remote-osf#10]
please add your username here if you want to join this project at any point. :)

**Comment by mih** [comment]
@mih

**Comment by DorienHuijser** [comment]
@DorienHuijser

**Comment by bpoldrack** [comment]
@bpoldrack

**Comment by nbeliy** [comment]
@nbeliy

**Comment by marcobarilari** [comment]
@marcobarilari

**Comment by mjboos** [comment]
@mjboos

**Comment by SRSteinkamp** [comment]
@srsteinkamp

**Comment by martsc1** [comment]
@martsc1

**Comment by kousu** [comment]
@kousu

**Comment by fedefalag** [comment]
@fedefalag

**Comment by mih** [comment]
Everyone until here should have received an invite to collaborate on https://github.com/datalad/datalad-osf

**Comment by DorienHuijser** [comment]
@all-contributors please add @adswa for projectManagement maintenance code doc

**Comment by mih** [comment]
It would make sense to me to put in people's info into https://github.com/datalad/datalad-osf/blob/master/.zenodo.json for an eventual publication. But we might just collect it in this repo first and transfer later.

**Comment by adswa** [comment]
> le's info into https://github.com/datalad/datalad-osf/blob/master/.zenodo.json for an eventual publication. But we might just collect it in this repo first and transfer later.

I will create an issue about this.

**Comment by TheDragon246** [comment]
@TheDragon246

**Comment by mih** [comment]
@TheDragon246 added you too!

**Comment by ayrustogaru** [comment]
@ayrustogaru

**Comment by adswa** [comment]
This has served its purpose :+1:
