### ISSUE TITLE
Exploring the utility of osfclient

### ISSUE THREAD

**Issue by mih** [adswa/git-annex-remote-osf#11]
Everything works, but the download of files

Starting point for fixing things: https://github.com/osfclient/osfclient/issues/144#issuecomment-644657071

Moreover, `osfclient` makes the impression to support token-based access, but actually doesn't.

**Comment by mih** [comment]
Sadly, just replacing the URL to the one reporting by OSF doesn't work.

**Comment by adswa** [comment]
would it make sense to replace the URL with the URL from the OSF or waterbutler API?
e.g: 
http://files.osf.io/v1/resources/<node_id>/providers/<provider_id>/<id_or_path> as in
http://files.osf.io/v1/resources/jy4bd/providers/osfstorage/523402a0234 for waterbutler?

**Comment by nbeliy** [comment]
osfclient have 41 forks: https://github.com/osfclient/osfclient/network/members
Probably one of them fixes the issue

**Comment by adswa** [comment]
Fix is found!
https://github.com/osfclient/osfclient/issues/144#issuecomment-644692913

@mih is implementing a fix. We probably won't get it into the osfclient (seems a bit unmaintained), but we will try to submit a PR and maintain a working fork.

**Comment by mih** [comment]
PR with fix: https://github.com/osfclient/osfclient/pull/176

**Comment by adswa** [comment]
Milestone 1 achieved: Have a client for up- and download

**Comment by nbeliy** [comment]
I get error 404 using osfclient, the username is the email, right?

**Comment by adswa** [comment]
yes @nbeliy

**Comment by adswa** [comment]
As the OSF client is successfully fixed in https://github.com/mih/osfclient I will close this. Thanks to everyone involved, its fantastic to have the osfclient working!
