### ISSUE TITLE
Add the extension we develop to the datalad handbook

### ISSUE THREAD

**Issue by adswa** [adswa/git-annex-remote-osf#12]
DataLad extension development will happen in https://github.com/datalad/datalad-osf
It would be cool to add this extension into the table in http://handbook.datalad.org/en/latest/extension_pkgs.html.

Please ping me if you want to tackle this. :) Requires: Basic Git, basic knowledge of Sphinx and restructured text markup.

Here is the repository to PR a change to: https://github.com/datalad-handbook/book
Find out more about how to contribute to this repository in http://handbook.datalad.org/en/latest/contributing.html

**Comment by ayrustogaru** [comment]
@adswa can I work on this?

**Comment by adswa** [comment]
Sure!

**Comment by adswa** [comment]
Let me know if you have questions :)

**Comment by ayrustogaru** [comment]
A question!! What exactly do I write in the description of the extension?🤔

**Comment by adswa** [comment]
A good question! :wink:
Let's keep it brief for now. Something along the lines of "A datalad extension to interface and work with the open science framework" (with a link to the OSF), and a reference to the github repository it is developed in https://github.com/datalad/datalad-osf would be good :)

**Comment by adswa** [comment]
done in https://github.com/datalad-handbook/book/pull/527
