### ISSUE TITLE
add contributors Orcid, affiliation, and name to extension's .zenodo.json file

### ISSUE THREAD

**Issue by adswa** [adswa/git-annex-remote-osf#14]
1. Collect contributors information in #10 
2. Add contributors information to https://github.com/datalad/datalad-osf/blob/master/.zenodo.json for an eventual publication.
3. Make sure that the file stays valid json (e.g., by checking with online validators or tools such as [jq](https://stedolan.github.io/jq/)

**Comment by adswa** [comment]
This would be really cool to have! @DorienHuijser @TheDragon246 @SRSteinkamp - if anyone of you would be up to it, that would be fantastic! Involves asking everyone for their orcid, affiliation, and full name, and adding it to the .zenodo.json file. With this, we might just cut a release today and publish it :)

**Comment by adswa** [comment]
Benjamin's, Michael's, and mine can be found here: https://github.com/datalad/datalad/blob/master/.zenodo.json, you would have to put in your own for yourself and ask everyone else for theirs.

**Comment by TheDragon246** [comment]
Sure! I would try to do this and ask for help (inevitably) if needed.

**Comment by TheDragon246** [comment]
@adswa Can you update once on which license type to add there?

**Comment by adswa** [comment]
MIT, see: https://github.com/datalad/datalad-osf/pull/62

**Comment by TheDragon246** [comment]
should issue a PR right now and issue another when other contributors provide details? Or wait? @adswa

**Comment by adswa** [comment]
do it now :)

**Comment by adswa** [comment]
I will close this issue as the PR is started and I'm cleaning up this repo now.
