### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by DorienHuijser** [adswa/git-annex-remote-osf#15]
Use this issue to add contributors to the readme.md file in this repository using the **add-contributors bot**. See the [emoji key](https://allcontributors.org/docs/en/emoji-key) for the different contributions.

Format:
`@all-contributors please add @gitusername for contribution1 contribution2`

Example:
`@all-contributors please add @adswa for projectManagement maintenance code doc`

**Comment by adswa** [comment]
hey @all-contributors please dd @DorienHuijser for doc projectManagement ideas userTesting maintenance

**Comment by adswa** [comment]
haha, sorry
hey @all-contributors please add @DorienHuijser for doc projectManagement ideas userTesting maintenance

**Comment by adswa** [comment]
We will migrate the allcontributors collected in here into the datalad extension later :+1:

**Comment by adswa** [comment]
cool, this is set up and migrated - thanks a lot @DorienHuijser !
