### ISSUE TITLE
Make outline of documentation

### ISSUE THREAD

**Issue by DorienHuijser** [adswa/git-annex-remote-osf#18]
For the documentation, let's make an outline so that we can get started on the separate components!

**Comment by adswa** [comment]
You can also find a bit of guidance and todos in https://github.com/datalad/datalad-osf/pull/11/files

**Comment by SRSteinkamp** [comment]
Ok let's start this.
So I've been looking at some of the other extensions, so I think we need:
- [ ] General introduction (landing page, short paragraph what it's about)
- [ ] A more in depth documentation of the code / technical side
- [ ] A demo / usecase for the different aspects which are implemented. 

More discussion - etc. are wellcome :) 

Wrong issue...

**Comment by TheDragon246** [comment]
For general introduction we would start with brief explanation of datalad, osf and an brief example to integrate them?

**Comment by adswa** [comment]
I also think it would be wonderful to add to the introduction that this was born at the OHBM 2020 Hackathon :)

**Comment by SRSteinkamp** [comment]
So I got a question about working on the todos documentation (like issue 11)  this means changes to the doc-strings or it's own documentation page?

**Comment by adswa** [comment]
Ideally, both :+1:

**Comment by SRSteinkamp** [comment]
If nobody else is already on it, I will go and tackle the index.rst and maybe we find some more organization in there :)

**Comment by DorienHuijser** [comment]
In terms of files (proposal):
- index.rst: Landing page? Very short intro to what the extension is and links to other pages? - beginning made bu @SRSteinkamp in [PR #22](https://github.com/datalad/datalad-osf/pull/22)
- introduction.rst (is now called intro.rst, but I think it appears as intro in the content as well):
  - Goal of the tool
  - What can I use this tool for?
  - What can I not use this tool for?
- settingup.rst: software/iinstallation requirements in clear steps and with links to instructions written down elsewhere (arranged per OS). This will probably be what I just did: installing mininaconda, datalad, python, git but also the osfclient
- running.rst: instructions on how to actually use the tool once everything is installed (details to be provided by the technical team)
- example.rst: a use case as proposed by @SRSteinkamp 
- contact.rst: acknowledgements and instructions on how to contribte
What do you think?

**Comment by TheDragon246** [comment]
* For introduction.rst: 
-Goal of the tool: To extend git-annex special remote implementation to Open Science Framework (OSF). This allows for OSF repository to be accessible via repository hosting services, and allows for direct access to OSF stored data via a repository hosting API, for example `git clone` in Github.
-What can I use this tool for?: The tool is most beneficial for easy access to data stored on OSF via Github. If you are sharing your dataset via OSF and code via Github, this will allow smooth integration of both along with unified version management provided by Datalab.
-What can I not use this tool for?: If your data is stored in a storage service other than OSF. Please refer [here](https://git-annex.branchable.com/special_remotes/) for a list of supported data storage services via git-annex special remote framework.

* For settingup.rst: We can take the instruction directly from [here](http://handbook.datalad.org/en/latest/intro/installation.html#install)?

**Comment by DorienHuijser** [comment]
@TheDragon246 Looks great as a start! Can you look at [PR 27](https://github.com/datalad/datalad-osf/pull/27) and add your content in the .rst-files that I made in there? 

For the settingup.rst file, I don't think we should copy the instructions from there, just refer to the website so that the instructions will always be up to date. 

I'm currently looking at how osfclient works and will still look into what exactly git-annex is, so the settinup.rst and running.rst pages will not receive much content from my part yet ;)

**Comment by SRSteinkamp** [comment]
Just a comment: I think the osfclient is now in the requirements, so it should be automatically installed. We might want to add something there, that this currently a fork of the not-so-well maintained main repro. 

For use cases here is some inspiration:
http://handbook.datalad.org/en/latest/basics/101-138-sharethirdparty.html

http://handbook.datalad.org/en/latest/usecases/using_globus_as_datastore.html

**Comment by adswa** [comment]
As an update from the call right now:
Taking the darft PR from @SRSteinkamp  (https://github.com/datalad/datalad-osf/pull/45) as a base, the docs team will outline the two usecases that this project is now capable of doing:
1. Using the OSF as an annex for a dataset (thus publishing the data into an OSF project as an object tree - not a pretty representation, but allows to store the entire history of the data on the OSF)
2. Exporting one state of the dataset into the OSF (thus publishing the data in a human readable way, but without the version control features)

Convenience helpers to do this are coming around soon!

Maybe important to check/mention: I believe OSFstorage is not limited in total size, but individual files can only be 5GB or less. It would be good if someone could check, and if its added to the documentation :)

**Comment by adswa** [comment]
I will clean up this coordination repository now and close all issues. Doc-related discussions move to https://github.com/datalad/datalad-osf
