### ISSUE TITLE
Create OSF projects for testing

### ISSUE THREAD

**Issue by adswa** [adswa/git-annex-remote-osf#2]
Create a public and a private project on the Open Science Framework for us to play with. The more comprehensive this task is carried out, the better. 

Please link these repositories here, and add team members to private repositories as necessary.

Here's a sketch of what is necessary: Add (any) data (honestly, any - cat content, your favorite recipe, a funny video, ...) to different storage providers (OSFStorage, GDrive, Dropbox, ...) to a public and a private repository on the OSF. Make sure that some data exists in a single version, but also take data and update it with a modified version, using the [OSF's version control features](https://help.osf.io/hc/en-us/articles/360019738694-file-revisions-and-version-control)

**Comment by nbeliy** [comment]
Created a user on OSF. Login emai and password are in mattermost chat.

I have a syntetic dataset that I can upload, but for some reason I can't uppload folders in web interface
