### ISSUE TITLE
Set-up documentation

### ISSUE THREAD

**Issue by adswa** [adswa/git-annex-remote-osf#4]
Software requires good documentation! The special remote implementation needs documentation, e.g., with [Mkdocs](https://www.mkdocs.org/), [readthedocs.org](readthedocs.org/), as a comprehensive README, as a tutorial, or as a usecase in [the datalad handbook](handbook.datalad.org/).

Tackling this issue does not mean to provide complete documentation. Comment in this issue to voice interest first, proceed in small steps, and reach out to others for help. Simply setting up the documentation for example is already huge!

**Comment by adswa** [comment]
Docs can be found at: http://docs.datalad.org/projects/osf/en/latest/

**Comment by SRSteinkamp** [comment]
Ok let's start this.
So I've been looking at some of the other extensions, so I think we need:
- [ ] General introduction (landing page, short paragraph what it's about)
- [ ] A more in depth documentation of the code / technical side
- [ ] A demo / usecase for the different aspects which are implemented. 

More discussion - etc. are wellcome :)

**Comment by adswa** [comment]
Done, linked, and coming along greatly in extension repo - closing.
