### ISSUE TITLE
Relevant info and pointer about the OSF, waterbutler, and git-annex special remotes

### ISSUE THREAD

**Issue by adswa** [adswa/git-annex-remote-osf#6]
Let's use this issue to collect useful pieces of information, links, and other pointers to relevant resources for the OSF API and special remote implementations.

If you find or know something of interest to this project, please add it as a comment here.

**Comment by adswa** [comment]
Read about the external special remote protocol: https://git-annex.branchable.com/design/external_special_remote_protocol/

Important points to keep in mind:
- Communication is via stdin and stdout. Therefore, the external special remote must avoid doing any prompting, or outputting anything like eg, progress to stdout. (Such stuff can be sent to stderr instead.)
- Each protocol line starts with a command, which is followed by the command's parameters (a fixed number per command), each separated by a single space. The last parameter may contain spaces. Parameters may be empty, but the separating spaces are still required in that case.
- The following requests **must** all be supported by the special remote: INITREMOTE, PREPARE, TRANSFER STORE|RETRIEVE Key File, CHECKPRESENT Key, REMOVE Key
- The following requests **can** be supported (else, the special remote can reply with UNSUPPORTED-REQUEST): EXTENSIONS List, LISTCONFIGS, GETCOST, GETAVAILABILITY, CLAIMURL Url, CHECKURL Url, WHEREIS Key, GETINFO
- **Optional and potentially the way to go**: tree exports and imports. Here is more about import and export: https://git-annex.branchable.com/design/external_special_remote_protocol/export_and_import_appendix/, specifically:

> When a special remote interfaces with something that looks like a directory of files, the simple export interface can be implemented to allow the git-annex-export command to be used to store file trees on the special remote.

and
> Normally files are stored on a git-annex special remote named by their keys. That is great for reliable data storage, but your filenames are obscured. Exporting replicates the tree to the special remote as-is.

The downside to an export are outlined here:
> Once content has been exported to a remote, commands like git annex get can download content from there the same as from other remotes. However, since an export is not a key/value store, git-annex has to do more verification of content downloaded from an export. Some types of keys, that are not based on checksums, cannot be downloaded from an export. And, git-annex will never trust an export to retain the content of a key.

However...
> However, some special remotes, notably S3, support keeping track of old versions of files stored in them. If a special remote is set up to do that, it can be used as a key/value store and the limitations in the above paragraph do not apply. Note that dropping content from such a remote is not supported. See individual special remotes' documentation for details of how to enable such versioning.

So given the versioning capabilities of the OSFstorage, we may be able to use a tree export (to not obscure file names), without loosing the version control features. But this requires more reading into the OSF.

- claiming custom uri schemes for use with git-annex addurl: If a special remote has its own uri scheme, or some other way to identify a particular url as being content that is stored in the special remote, and can be downloaded by it, it can implement CLAIMURL and CHECKURL. This lets git-annex addurl be used with such urls.

Here is a template for git annex special remotes that implements the complete external remote protocol: https://github.com/Lykos153/AnnexRemote (see https://github.com/Lykos153/git-annex-remote-googledrive for a concrete implementation example). This template can also to export remotes.

Other than a special remote implementation, a [hook](https://git-annex.branchable.com/special_remotes/hook/) may be sufficient, too.

**Comment by adswa** [comment]
Waterbutler API docs: https://waterbutler.readthedocs.io/en/latest/api.html#v1-api
OSF API docs: https://developer.osf.io/#section/https:api.osf.iov2

**Comment by mih** [comment]
This might be another starting point: https://github.com/psychopy/pyosf

**Comment by adswa** [comment]
Relevant authentication section in the OSF API: https://developer.osf.io/#tag/Authentication

**Comment by adswa** [comment]
In a short ad-hoc hacking session, @mih was able to list, create new, overwrite, upload, and remove files from a private project on the OSF -- but not download.

**Comment by adswa** [comment]
This served its purpose - closing.
